version: '3.9'

services:
  app:
    image: oghma:dev-latest
    container_name: oghma-dev
    restart: unless-stopped
    mem_limit: 512m
    env_file:
      - /home/semyon/jenkins/env/oghma-dev.env
    networks:
      - oghma

  worker:
    image: oghma-worker:dev-latest
    container_name: oghma-dev-worker
    restart: unless-stopped
    mem_limit: 512m
    env_file:
      - /home/semyon/jenkins/env/oghma-dev.env
    networks:
      - oghma

networks:
  oghma:
    external: true
